app/app.go

Not sure about the history but anyway unused handler.

comment: remove commented handler

---

app/app.go

Module dependency changed(math, dbm, log)
Function parameter changed
above two changes seem ok
One logical change is the addition of `PreBlock`, which runs before `BeginBlock`. According to docs,`upgrade` module seems to be placed in it

Changes required for app.go file in cosmos-sdk 0.50

---

.github/dependabot.yml

Reverts hippocrat-dao/hippo-protocol#110

Revert "chore: ignore npm packages for dependabot"

---

.github/workflows/go.yml

Init action to check whether build is successful.
@0114kek we can add test command.
@muzaf-dev @DJ-Hippo  we can add hippod command check.

chore: add build process for go

---

app/inflation_test.go
test/inflation_test.go

This test is for `CustomInflationCalculationFn`
The unit test has 4 scenario, differing block heights.
It compares calculated inflation rate with theoretical inflation rate
You can run test inside `app` directory by running `go test -v`

test: test for CustomInflationCalculationFn

---

.github/workflows/go.yml

Add `go test -v ./test` for go workflow.

chore: add test workflow

---

hippod/main_test.go
test/main_test.go

Add TestMainCommand integration test
- Implement basic integration test using exec.Command
- Test execution of main command in specified directory

test: add testMainCommand integration test

---

.github/workflows/go.yml

Test integration for all directory.
reference: https://stackoverflow.com/questions/19200235/golang-tests-in-sub-directory

chore: test go all the directory

---

.github/workflows/go.yml

chore: add coverage test for go.yml

---

app/app_test.go
go.mod

Currently only checking the liveness of functions. We should add more detail later, the correctness of return values.

test: add test for app.go

---

app/keys_test.go
hippod/cmd/init_test.go

We must reverse logic for initCmd later.

test: add initCmd as just set up

---

test/helper_test.go

Added TestGetApp to helper_test.

test: add test for helper.go

---

app/export_test.go

Added TestPrepForZeroHeightGenesis_NotNil to export_test.

test: add test for export.go

---

app/app_test.go

Added TestInitChainer_InvalidJSON to app_test.

test: add testInitChainer for app.go

---

app/ante_test.go
app/app_test.go

Added TestSetAnteHandler to ante_test.

test: add test for ante.go

---

hippod/cmd/root_test.go

Added TestAppExport to hippod/cmd/root_test.

test: add test for root.go

---

hippod/cmd/genaccounts_test.go

Added TestAddGenesisAccountCmd_InvalidVestingParameters to hippod/cmd/genaccounts_test.

test: add test for genaccounts.go

---

hippod/cmd/init_test.go

overrideGenesis and displayInfo is 100% coverage now.

test: failing test for overrideGenesis and displayInfo

---

docs/docs/hub-tutorials/join-mainnet.md
docs/docs/validators/validator-setup.md

In our docs, I updated the `Joining mainnet` section and `Running a validator` section.
As our testnet version is different from main branch now, error occured when I'm starting node after following docs. So there can exist some wrong contents. If you find it, please let me know.

docs: update docs about running node

---

.github/workflows/go.yml

- separate build and test task
- set threshold(80%) for test
From now, code change with test coverage below 80% will fail ci.

chore: separate build and test, set threshold for test

---

.github/workflows/go.yml
test/e2e/cli_test.go

~This is DRAFT!~
Currently only include e2e test set up for ci pipeline.
@0114kek plz check bash script below, and try to integrate https://github.com/hippocrat-dao/hippo-protocol/pull/145 into this branch(just push commits).
You should check https://github.com/ChrisCho-H/hippo-protocol/blob/main/test/e2e/cli_test.go. You can find out how to use keyring backend of operating node to send transaction.

test: set up blockchain environment for e2e

---

test/e2e/cli_test.go

- add more staking related e2e test case
- change to use bignumber when comparing token amount

test: add additional tests and fix number comparison

---

test/e2e/cli_test.go

testing the edit-validator CLI.
sadly we can't test changing the commission_rate of validator. It seems at least 24 hour after the validator created, we can change it

test: add edit-validator test

---

.github/workflows/deploy-docs.yml

Deploy docs
- The deployment is triggered when changes are made to the docs folder or the workflow file itself on the main branch.

chore: add docs deployment YAML files

---

test/e2e/cli_test.go

Test for generating proposal json and submitting using cli.

test: add test for governance proposal

---

.github/workflows/go.yml
test/e2e/api_rpc_test.go

Below testcases is for the apis and rpcs that we are using in hippo river.
To enable api in CI, I also modified workflows a little

Testing api ,rpc

---

README.md

docs: add security docs

---

.gitignore
.goreleaser.yaml
Makefile

currently integration with Ci not done.
see our notion for more details

goreleaser for release

---

app/app.go
app/upgrades/v1_0_1/constants.go
app/upgrades/v1_0_1/upgrade.go

Added Upgrade handler for v1.0.1

feat: add upgrade handler for v1.0.1

---

sdk/core/Cargo.toml
sdk/core/src/lib.rs
sdk/core/src/tests/rust.rs
sdk/core/src/types.rs

Add pedersen commit and verify function to build homomorphic and zkp features.

feat: add pedersen commit and verify function
