hippo-protocol/hippo-protocol

types/consensus/policy.go
In total inflation, only 8% goes to distr module account(validator + delegator).
Make community tax precise according to HIP-2.
=> feat: community tax to 92%

types/consensus/policy.go
According to [PBFT paper](https://pmg.csail.mit.edu/papers/osdi99.pdf), there must be `3f + 1` nodes when `f` is malicious. According to [hyperledger](https://github.com/hyperledger-archives/sawtooth-rfcs/blob/main/text/0019-pbft-consensus.md#motivation), if `f` is not integer(has decimal point), it should floor. It means that if we set validator of 21, we can tolerate 6 malicious nodes, while we can 7 if set validator of 22, theoretically. However, it doesn't exactly match with dpos blockchain as its right to produce and validate block(message) is weighted with staked token(above description would only work if all validator has same weight). [Tendermint](https://docs.tendermint.com/v0.34/introduction/what-is-tendermint.html) adopts dpos with pbft, so practically it's not that meaningful …
=> feat: improve tolerability by allowing upto 7 malicious validators

types/consensus/policy.go
Following https://github.com/hippocrat-dao/hippo-protocol/issues/61, increase the minimum uptime requirement.
I'm not sure whether 50% is still too generous(maybe at least 75% would be ideal), just think it'd be better to leave a room to increase for the time when our blockchain matures.
Open to any opinion! I'm still figuring out as well.
=> feat: min uptime 75% while not slash for downtime

sdk/core/.gitignore, sdk/core/Cargo.toml, sdk/core/src/main.rs
Add hippo-sdk directory as monorepo(inside the hippo-protocol), supporting some essential protocol-related methods independent from the blockchain core node, for faster and safer implementation.
Plan to support the interface for various languages, on the basis of compiled binary of rust.
It's basically library but with more intensive features and symbolic semantics.
=> feat: init hippo sdk

sdk/core/Cargo.toml, sdk/core/src/main.rs
Implement cryptography(encrypt, decrypt, sign, verify...) logic for sdk.
It might be bit hard to understand, so feel free to ask any question.
KeyPair: secp256k1(elliptic curve widely used in crypto)
Enc(Dec)ryption: ecies(ecdh + aes-gcm)
Also add ecdh for sdk as it seems to be useful(e.g. user and institute generate shared secret key).
=> feature: hippo sdk initial implementation for cryptography

docs/docs/delegators/delegator-faq.md, docs/docs/getting-started/README.md, docs/docs/getting-started/_category_.json, docs/docs/getting-started/installation.md, docs/docs/getting-started/what-is-hippo.md, docs/docs/governance/current-parameters.js, docs/docs/governance/proposal-types/community-pool-spend.md, docs/docs/governance/submitting.md, docs/docs/hub-tutorials/join-mainnet.md, docs/docs/index.md, docs/docs/resources/genesis.md, docs/docs/resources/service-providers.md, docs/docs/validators/overview.md, docs/docs/validators/validator-faq.md, docs/docs/validators/validator-setup.md
Following the discussion in https://github.com/hippocrat-dao/hippo-protocol/issues/70,
- revive `getting-started` docs, which also includes guideline to use `hippod` command.
- fix some wrong contents
- add hippo river url for any explorer related link.
=> docs: hippo-protocol docs v0.1

app/app.go, app/export.go, app/keepers/keepers.go, app/keepers/keys.go, hippod/cmd/init.go, types/consensus/policy.go
- [af16263c4d96acb6c3176394821fb8df91de8d89](https://github.com/hippocrat-dao/hippo-protocol/commit/af16263c4d96acb6c3176394821fb8df91de8d89): max block size limit decrease to 4mb to prevent DoS
related issue: https://github.com/hippocrat-dao/hippo-protocol/issues/75
- [9e8987f9b5540279710ba79fdd46a6bc9e9a2a17](https://github.com/hippocrat-dao/hippo-protocol/commit/9e8987f9b5540279710ba79fdd46a6bc9e9a2a17): max block gas limit decrease to 100 mil to prevent DoS
related issue: https://github.com/hippocrat-dao/hippo-protocol/issues/73
- [1d85b651e37f77e901be9ded8e99b49db91c37ec](https://github.com/hippocrat-dao/hippo-protocol/pull/76/commits/1d85b651e37f77e901be9ded8e99b49db91c37ec): bech32 prefix must be hippo instead of cosmos.
related issue: …
=> fix: limit for max block and gas, remove crisis module, fix account keeper bech32 prefix, extend evidence param

app/app.go, app/inflation.go
**Resolve 2 Informational Severities**
1. Redundant definition of MakeEncodingConfig function
- The makeEncodingConfig function was defined in both app/app.go and app/encoding.go. This duplication increases maintenance complexity and risks inconsistencies.
- The redundant definition in app/app.go is removed, and references have been updated to use the implementation in app/encoding.go.
2. Use of magic numbers decreases maintainability
- Hard-coded number literals without context or description (magic numbers) are used in app/inflation.go, reducing code readability and maintainability.
- To enhance readability and maintainability, these numbers have been replaced with well-documented constants
=> refactor: remove duplicate makeEncodingConfig & define magic number constants

app/export.go, app/inflation.go, app/keepers/keys.go
Luckily, there seems to be only slight semantic change(type, naming, returning err with value) across inflation.go, export.go, key.go.
=> feature: v0.50 for inflation, keys, export files

app/inflation.go
Even if we have `sdk.Context` across our files, cosmos-sdk deprecated and recommend using the alternative, according to [UPGRADING docs](https://github.com/cosmos/cosmos-sdk/blob/548ca00b11f89145fc112e54e680f6710172bb5a/UPGRADING.md#core-api).
Seemingly, other codes containing `sdk.Context` are not affected, but inflation function interface replace the parameter type of `sdk.Context` by `context.Context`, which causes API break....lol. 
I've figured out the way to use the `sdk.Context` as it has been like below, which is necessary to get realtime block height .
```go
// sdk.Context is deprecated in v0.50
// https://github.com/cosmos/cosmos-sdk/blob/548ca00b11f89145fc112e54e680f6710172bb5a/UPGRADING.md#core-api
ctx := sdk.UnwrapSDKContext(context)
```
=> feat: sdk.Context deprecated and inflation fn interface changed

.github/dependabot.yml
Our [dependabot](https://github.com/hippocrat-dao/hippo-protocol/security/dependabot) checks all the scope of repo including`docs/**`, which makes the irrelevant noise for our core code. Use dependabot.yml to exclude the npm packages of `docs/**`.
=> chore: add dependabot.yml to exclude docs in monitoring

.github/dependabot.yml
Our [dependabot](https://github.com/hippocrat-dao/hippo-protocol/security/dependabot) checks all the scope of repo including `docs/**`, which makes the irrelevant noise for our core code. Use dependabot.yml to exclude the npm packages to ignore `docs/**`.
Seems to be `exclude-patterns` not supported any more. https://stackoverflow.com/questions/65275433/can-i-exclude-directories-from-github-dependabot
=> feat: add dependabot yml

.github/dependabot.yml
Finally figured out to ignore npm by testing my personal fork.
https://github.com/ChrisCho-H/hippo-protocol
=> chore: exclude all npm monitoring

hippod/cmd/root_test.go
This pull request includes several changes to the `hippod/cmd/root_test.go` file to enhance the test coverage and improve the setup process for tests. The most important changes include adding necessary imports, creating a mock application options type, and setting up a new test for application initialization.
Enhancements to test coverage and setup:
* Added necessary imports for `bytes`, `os`, `path/filepath`, and `github.com/cosmos/cosmos-sdk/server` to support new test functions.
* Created a `mockAppOptions` type to simulate application options for testing purposes. This includes a `Get` method to retrieve option values.
* Added a `setupGenesisFile` function to create a temporary directory and generate a minimal genesis file for testing.
* Introduced a `TestNewApp` function to test the …
=> wrote test case for root's newApp

README.md, docs/docs/getting-started/installation.md
This pull request includes updates to the documentation to clarify the creation of a new key using the file backend for secure local key storage. The most important changes are in the `README.md` and `docs/docs/getting-started/installation.md` files.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L19-R20): Updated the instructions for creating a new key to mention the use of the file backend for secure local key storage and emphasized the importance of saving the generated address.
* [`docs/docs/getting-started/installation.md`](diffhunk://#diff-86a5e1e7e6ba037634309d7205a4cc8f03359c76601e155c711b14e6d8eee150L20-R21): Similar update to the instructions for creating a new key, specifying the use of the file backend …
=> update: add keys in secure way

hippod/cmd/genaccounts_test.go
This pull request includes changes to the `hippod/cmd/genaccounts_test.go` file to improve the organization and coverage of the tests. The most important changes include reorganizing the package structure, enhancing test coverage, and refining the test cases.
* Changed the package declaration from `cmd` to `cmd_test` to follow Go's best practices for testing.
* Refactored the `TestAddGenesisAccountCmd` function to `TestAddGenesisAccountCmd_FullCoverage` and added multiple test cases to cover various scenarios, including invalid coins, vesting parameters, and successful account creation.
These changes improve the maintainability and reliability of the tests by ensuring a more comprehensive coverage of different scenarios.
=> test: improved genaccounts test coverage

hippod/cmd/init_test.go
This pull request includes significant updates to the `hippod/cmd/init_test.go` file, focusing on restructuring the imports, updating the initialization command, and improving the test cases. The most important changes are summarized below:
* Reorganized and updated import statements to include necessary packages from `cosmos-sdk` and removed unused imports.
* Replaced the old initialization command and related functions with a new `InitCmd` that uses `module.NewBasicManager` and supports additional modules such as `auth`, `bank`, `staking`, `mint`, `gov`, `slashing`, and `distribution`.
* Added a `makeTestEncodingConfig` function to create a codec with registered interfaces for various modules.
* Updated the `TestInitCmd_Basic` test case to use the new initialization command and verify …
=> test: init test cases updates with real cases for improve %

README.md, docs/docs/getting-started/installation.md
`--keyring-backend file` must be included every use of wallet related.
=> docs: keyring backend file must be used every time

hippod/cmd/root_test.go
This pull request includes several updates to the `hippod/cmd/root_test.go` file to enhance the test coverage and improve the command handling. The most important changes include adding new import statements, updating the `TestNewRootCmd` function, and adding multiple new test functions.
Enhancements to test coverage and command handling:
* [`hippod/cmd/root_test.go`](diffhunk://#diff-fc03a8ca45d55dce14f30b509e512282de90241355ddb54d9016d93ee4889f3eR7): Added new import statements for `strings`, `module`, `tx`, and `genutil` to support the new test cases. [[1]](diffhunk://#diff-fc03a8ca45d55dce14f30b509e512282de90241355ddb54d9016d93ee4889f3eR7) [[2]](diffhunk://#diff-fc03a8ca45d55dce14f30b509e512282de90241355ddb54d9016d93ee4889f3eR16-R54)
* …
=> test: NewRootCmd test case improved

hippod/cmd/init.go, types/consensus/policy.go
- 845ee9bcf4dc9f7f6fe8f08b53d3aa9004f35e14
register metadata to fix bug regarding https://github.com/hippocrat-dao/hippo-protocol/issues/59.
- f212dc950e505cf03392351fd183d04c57e06429
set expedited min deposit which wrongly use default "stake" denom.
=> fix: override genesis for min deposit and meta data

app/app.go, hippod/cmd/init.go
This fix the issue of empty(or broken) app name and version of genesis.json.
Moreover, we can explicitly upgrade version in the future.
=> feat: set version and name explicitly
